#!/bin/sh /etc/rc.common
START=11
[ -n "${IPKG_INSTROOT}" ] && return 0
grep(){
/bin/busybox 'grep' $@
}
for i in $( ls /sys/class/net/*/device/uevent | awk -F'/' '{print $5}' | tr '\n' ' ' ) ;
do	
mac_address=$( grep $i /etc/config/mac-todong | awk '{print $3}' | tr -d '"' )	
if [ "$mac_address" != '' ]; then			
ip link set "$i" down 		
ip link set "$i" name old"$i"			
fi
done
for i in $( ls /sys/class/net/*/device/uevent | awk -F'/' '{print $5}' | tr '\n' ' ' ) ;
do
mac_address=$( cat /sys/class/net/$i/address  )	
interface_name=$( grep -i $mac_address /etc/config/mac-todong | awk '{print $2}' )	
if [ "$interface_name" != '' ]; then			
ip link set "$i" down 		
ip link set "$i" name "$interface_name"			
fi
done
